# Generated by Django 2.2 on 2020-01-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(choices=[(0, 'NR - Not Rated'), (1, 'G - General Audience'), (2, 'PG - Parental GuidanceSuggested'), (3, 'R - Restricted')], default=0),
        ),
    ]
